### PR TITLE
(Fix): Fixes condition for client side variables

### PR DESCRIPTION
**Pull request by pedroalmeida415**
This PR fixes one problem that I had while using it with Gatsby.js.
Basically it wasn't going through Gatsby's SSR step, saying that "the variable 'document' is not defined".

### CODE REVIEW

**Comment by icarus-sullivan** [comment]
Did you run this against the local example project? If not let me know and I'll test it.

**Comment by pedroalmeida415** [comment]
I tried to but couldn't get the example running, and it's probably best if you test it yourself as well

**Comment by icarus-sullivan** [comment]
Looks good m8, thanks for the PR.

**Comment by icarus-sullivan** [comment]
@pedroalmeida415 Closed this too quickly and forgot to update you. Just published v1.3.1 with your changes. Let me know if you have any more issues.

**Comment by pedroalmeida415** [comment]
Oh, no problem, great to see that it worked! I'll ping you if I get any other issue.

**Pull request merged**
